'use client';
import { use } from 'react';
import Link from 'next/link';
import { useQuery } from '@apollo/client';
import { GET_PLAYER } from '@/graphql/queries/players';
import { ProtectedRoute } from '@/components/auth/ProtectedRoute';
import { AppNavigation } from '@/components/layout/AppNavigation';
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { getPositionAbbreviation } from '@/utils/volleyballUtils';
import { ArrowLeft, Pencil, ClipboardCheck } from 'lucide-react';
const labels:Record<string,string>={serving:'Service',passing:'Réception',setting:'Passe',attacking:'Attaque',blocking:'Contre',defense:'Défense',power:'Puissance',accuracy:'Précision',consistency:'Régularité',control:'Contrôle',reception:'Réception',positioning:'Placement',tempo:'Tempo',decision:'Décision',precision:'Précision',variety:'Variété',technique:'Technique',timing:'Timing',reading:'Lecture',digging:'Défense basse',reflexes:'Réflexes',speed:'Vitesse',agility:'Agilité',flexibility:'Mobilité',strength:'Force',endurance:'Endurance',verticalJump:'Détente',gameIntelligence:'Lecture du jeu',communication:'Communication',leadership:'Leadership',mentalToughness:'Solidité mentale',coachability:'Capacité d’apprentissage'};
function Metrics({value}:{value:any}){if(!value)return <p className="text-muted-foreground">Aucune mesure enregistrée.</p>;return <dl className="space-y-3">{Object.entries(value).filter(([k,v])=>k!=='__typename'&&v!=null).map(([key,v])=><div key={key}>{typeof v==='object'?<section className="rounded-lg border p-4"><h4 className="font-medium mb-3">{labels[key]||key.replace(/([A-Z])/g,' $1')}</h4><Metrics value={v}/></section>:<div className="flex justify-between gap-5 text-sm"><dt className="text-muted-foreground">{labels[key]||key.replace(/([A-Z])/g,' $1')}</dt><dd className="font-semibold tabular-nums">{typeof v==='number'?Number(v.toFixed(1)):String(v)}</dd></div>}</div>)}</dl>}
export default function PlayerDetailPage({params}:{params:Promise<{id:string}>}){const {id}=use(params);return <ProtectedRoute><AppNavigation/><PlayerDetails id={id}/></ProtectedRoute>}
function PlayerDetails({id}:{id:string}){
 const {data,loading,error}=useQuery(GET_PLAYER,{variables:{id}});const p=data?.player;
 if(loading)return <main className="max-w-7xl mx-auto p-6" aria-busy="true">Chargement du joueur…</main>;
 if(error||!p)return <main className="max-w-7xl mx-auto p-6"><p role="alert">Cette fiche est introuvable ou inaccessible.</p><Link href="/players">Retour aux joueurs</Link></main>;
 const name=`${p.firstName} ${p.lastName}`;const date=p.dateOfBirth?new Date(p.dateOfBirth):null;const today=new Date();const age=date?today.getFullYear()-date.getFullYear()-(today.getMonth()<date.getMonth()||(today.getMonth()===date.getMonth()&&today.getDate()<date.getDate())?1:0):null;
 return <main className="astren-workspace min-h-screen"><div className="max-w-7xl mx-auto px-4 sm:px-6 py-6 space-y-6">
 {p.assessmentKind==='ESTIMATED'&&<p className="rounded-xl border border-primary/30 bg-primary/5 p-4 text-sm">Notes de départ estimées à partir du profil de l’effectif. Elles restent à confirmer par le coach et ne correspondent pas à des tests mesurés.</p>}
 {p.rosterTeamIds?.length>0&&<p className="text-sm text-primary">Effectif partagé : disponible pour les équipes B et C. Une seule fiche et un seul historique.</p>}
 <Link href="/players" className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft size={16}/>Retour à l’effectif</Link>
 <section className="flex flex-wrap items-center justify-between gap-6 rounded-2xl border bg-card p-5 sm:p-8"><div className="flex items-center gap-4 min-w-0"><Avatar className="w-16 h-16 sm:w-24 sm:h-24 text-3xl text-primary"><AvatarImage src={p.avatar||undefined} alt="" className="object-cover"/><AvatarFallback>{p.jerseyNumber??p.firstName[0]}</AvatarFallback></Avatar><div className="min-w-0"><p className="astren-eyebrow">{getPositionAbbreviation(p.primaryPosition)} {p.jerseyNumber!=null?`· #${p.jerseyNumber}`:''}</p><h1 className="font-medium text-3xl sm:text-5xl break-words" style={{fontFamily:'var(--font-astren-display),Georgia,serif'}}>{name}</h1><p className="text-sm text-muted-foreground mt-2">{age!==null?`${age} ans · `:''}{p.nationality} · {({ACTIVE:'Actif',INACTIVE:'Inactif',INJURED:'Blessé',SUSPENDED:'Suspendu'} as Record<string,string>)[p.status]||p.status}</p></div></div><div className="flex flex-wrap gap-2"><Button asChild variant="outline"><Link href={`/players/${id}/edit`}><Pencil/>Modifier</Link></Button><Button asChild><Link href={`/evaluation?playerId=${id}`}><ClipboardCheck/>Évaluer</Link></Button></div></section>
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Note actuelle',p.currentRating!=null?`${Number(p.currentRating).toFixed(1)} / 10`:'Non noté'],['Potentiel',p.potentialRating!=null?`${Number(p.potentialRating).toFixed(1)} / 10`:'Non évalué'],['Taille',p.height?`${p.height} cm`:'Non renseignée'],['Dernière évaluation',p.lastEvaluationDate?new Date(p.lastEvaluationDate).toLocaleDateString('fr-FR'):'À programmer']].map(([label,value])=><Card key={label}><CardContent className="p-4"><p className="text-xs text-muted-foreground mb-3">{label}</p><p className="text-lg sm:text-2xl font-semibold">{value}</p></CardContent></Card>)}</div>
 <Tabs defaultValue="overview"><TabsList className="grid grid-cols-4 w-full h-auto"><TabsTrigger value="overview">Suivi</TabsTrigger><TabsTrigger value="technical">Technique</TabsTrigger><TabsTrigger value="physical">Physique</TabsTrigger><TabsTrigger value="mental">Mental</TabsTrigger></TabsList>
 <TabsContent value="overview" className="space-y-5 mt-5"><div className="grid md:grid-cols-2 gap-5"><Card><CardHeader><CardTitle>Points forts & progression</CardTitle></CardHeader><CardContent className="space-y-5">{[['Points forts',p.strengths],['Axes de travail',p.weaknesses]].map(([title,items])=><section key={String(title)}><h3 className="font-medium mb-2">{String(title)}</h3>{Array.isArray(items)&&items.length?<ul className="space-y-1 text-sm text-muted-foreground">{items.map((v:string)=><li key={v}>· {v}</li>)}</ul>:<p className="text-sm text-muted-foreground">À renseigner lors d’une évaluation.</p>}</section>)}</CardContent></Card><Card><CardHeader><CardTitle>Informations du joueur</CardTitle></CardHeader><CardContent className="space-y-3">{[['E-mail',p.email],['Téléphone',p.phone],['Envergure',p.wingspan?`${p.wingspan} cm`:null],['Portée bras levés',p.armReach?`${p.armReach} cm`:null],['Notes du coach',p.notes],['Contact d’urgence',p.emergencyContact],['Téléphone d’urgence',p.emergencyPhone]].filter(([,v])=>v).map(([label,v])=><div key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="text-sm whitespace-pre-wrap break-words">{v}</p></div>)}{p.medicalNotes&&<details className="border-t pt-3"><summary className="text-sm cursor-pointer">Notes médicales · accès encadrement</summary><p className="mt-3 text-sm whitespace-pre-wrap">{p.medicalNotes}</p></details>}</CardContent></Card></div>
 <Card><CardHeader><CardTitle>Dernières notes enregistrées</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground mb-4">Les notes globales et les mesures des batteries sont suivies séparément.</p>{p.evaluations?.length?<ul className="divide-y">{p.evaluations.map((e:any)=><li key={e.id} className="py-3 flex justify-between gap-4"><span>{new Date(e.evaluationDate).toLocaleDateString('fr-FR')}</span><strong>{Number(e.overallRating).toFixed(1)} / 10</strong></li>)}</ul>:<p className="text-sm">Pas encore de note globale.</p>}<Link href="/evaluation" className="inline-block mt-4 text-sm text-primary underline underline-offset-4">Consulter les batteries de tests et leur historique</Link></CardContent></Card></TabsContent>
 {(['technical','physical','mental'] as const).map((key)=><TabsContent key={key} value={key} className="mt-5"><Card><CardHeader><CardTitle>{{technical:'Compétences techniques',physical:'Mesures et capacités physiques',mental:'Qualités mentales'}[key]}</CardTitle></CardHeader><CardContent><Metrics value={p[`current${key[0].toUpperCase()}${key.slice(1)}`]}/></CardContent></Card></TabsContent>)}
 </Tabs></div></main>;
}
