ALTER TABLE players ALTER COLUMN "dateOfBirth" DROP NOT NULL;
ALTER TABLE players ALTER COLUMN "jerseyNumber" DROP NOT NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS "rosterTeamIds" TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE players ADD COLUMN IF NOT EXISTS "assessmentKind" TEXT NOT NULL DEFAULT 'OBSERVED';
ALTER TABLE players ADD COLUMN IF NOT EXISTS "intakeProfile" JSONB;
CREATE TABLE IF NOT EXISTS coaching_data_imports (key TEXT PRIMARY KEY, source_hash TEXT NOT NULL, imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), summary JSONB NOT NULL);
